# Generated by Django 4.1.3 on 2022-11-23 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=25, null=True)),
                ('designation', models.TextField(blank=True, null=True)),
                ('salary', models.IntegerField(blank=True, null=True)),
                ('is_lead', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDiscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_doc', models.URLField()),
                ('project_design', models.URLField()),
                ('project_remark', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_time', models.TimeField()),
                ('project_budget', models.IntegerField()),
                ('is_completed', models.BooleanField()),
                ('project_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.projectdiscription')),
                ('project_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.employee')),
                ('working_hours', models.ManyToManyField(related_name='working_hours', to='app.employee')),
            ],
        ),
        migrations.AddField(
            model_name='projectdiscription',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.projects'),
        ),
        migrations.AddField(
            model_name='employee',
            name='assigned_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.projects'),
        ),
        migrations.AddField(
            model_name='employee',
            name='skills',
            field=models.ManyToManyField(related_name='skills', to='app.skills'),
        ),
        migrations.AddField(
            model_name='employee',
            name='team_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead', to='app.employee'),
        ),
    ]
