# Generated by Django 4.1.3 on 2022-11-23 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_lead', to='app.employee'),
        ),
    ]
