# Generated by Django 4.1.3 on 2022-11-23 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_projects_project_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='assigned_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.projects'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='skills',
            field=models.ManyToManyField(blank=True, null=True, related_name='skills', to='app.skills'),
        ),
    ]
