# Generated by Django 4.1.3 on 2022-11-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_employee_assigned_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='working_hours',
        ),
        migrations.AddField(
            model_name='projects',
            name='working_employee',
            field=models.ManyToManyField(related_name='working_employee', to='app.employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='skills',
            field=models.ManyToManyField(related_name='skills', to='app.skills'),
        ),
    ]
