# Generated by Django 4.1.3 on 2022-11-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_projects_working_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdiscription',
            name='project',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
