# Generated by Django 4.1.3 on 2022-11-23 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_projectdiscription_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='delivery_time',
            field=models.DateTimeField(),
        ),
    ]
