# Generated by Django 4.1.3 on 2022-11-24 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_projects_delivery_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='assigned_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_discription', to='app.projects'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proj', to='app.projectdiscription'),
        ),
    ]
