# Generated by Django 4.1.3 on 2022-11-24 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_employee_assigned_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='project_details',
        ),
    ]
