# Generated by Django 4.1.3 on 2022-11-24 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_employee_assigned_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proj', to='app.projectdiscription'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='assigned_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discription', to='app.projects'),
        ),
    ]
