# Generated by Django 4.1.3 on 2022-11-24 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_projects_project_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='skills',
            field=models.ManyToManyField(related_name='skill_name', to='app.skills'),
        ),
    ]
